version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start
    container_name: django-api
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - django.env
      - postgres.env
      - django-local.env
    depends_on:
      - postgres
    networks:
      - restauration-api

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    container_name: postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_NAME=restauration
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    networks:
      - restauration-api
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
    restauration-api:
        driver: bridge

volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}
    static_volume:
    media_volume: